// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_gOddlDtmOEsSwJgJKv95zmHg49FWzt4',
    appId: '1:412324001254:web:1eddaa0fb146e76d325227',
    messagingSenderId: '412324001254',
    projectId: 'pray-iafcj',
    authDomain: 'pray-iafcj.firebaseapp.com',
    storageBucket: 'pray-iafcj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr6jnZqEWWK7fhT76waxrLQrjuy_04UtU',
    appId: '1:412324001254:android:e344cccd0e1fafa2325227',
    messagingSenderId: '412324001254',
    projectId: 'pray-iafcj',
    storageBucket: 'pray-iafcj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB1tThEGNB28P0FsHMaOs-hRm0JlDKJGk',
    appId: '1:412324001254:ios:660b9f53700c945f325227',
    messagingSenderId: '412324001254',
    projectId: 'pray-iafcj',
    storageBucket: 'pray-iafcj.firebasestorage.app',
    iosBundleId: 'com.example.prayIafcj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB1tThEGNB28P0FsHMaOs-hRm0JlDKJGk',
    appId: '1:412324001254:ios:660b9f53700c945f325227',
    messagingSenderId: '412324001254',
    projectId: 'pray-iafcj',
    storageBucket: 'pray-iafcj.firebasestorage.app',
    iosBundleId: 'com.example.prayIafcj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_gOddlDtmOEsSwJgJKv95zmHg49FWzt4',
    appId: '1:412324001254:web:6ccf26f1602ed65f325227',
    messagingSenderId: '412324001254',
    projectId: 'pray-iafcj',
    authDomain: 'pray-iafcj.firebaseapp.com',
    storageBucket: 'pray-iafcj.firebasestorage.app',
  );
}
